[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "unbundle"
version = "v1.1.1"
license-files = ["LICENSE"]
readme = "README.md"

[project.scripts]
unbundle = "unbundle:main"
